### ISSUE TITLE
Database tests are not persisting tables correctly in test.db

### ISSUE THREAD

**Issue by RezaBG** [RezaBG/TUDU#27]
### Problem Description
The `test.db` database file is created during tests but does not persist the `users` and `tasks` tables after the test execution. When inspecting the database, no tables are found.

### Steps to Reproduce
1. Run the `pytest tests` command.
2. Inspect the `test.db` file using SQLite:
    ```bash
    sqlite3 ./test.db
    .tables
    ```
3. Observe that no tables are created in the database.

### Expected Behavior
The `users` and `tasks` tables should persist in `test.db` after the tests complete.

### Observed Behavior
The `test.db` file exists, but running `.tables` shows no tables.

### Additional Context
This issue may be related to the `Base.metadata.drop_all()` function in the `setup_db` or `reset_database` fixtures in `tests/conftest.py`.

**Comment by gnerkus** [comment]
This is expected behaviour.

Test are usually designed to be run in isolation this means:
1. tear up creates the tables and entities
2. test is run
3. tear down removes the entities and drops the tables

This ensures that a test is reproducible: it returns the same results given the same inputs.

**Comment by RezaBG** [comment]
Thanks Iffy @gnerkus 

Thanks for the explanation—that makes a lot of sense now. I get why teardown is crucial for keeping tests isolated and reproducible.

If I want to debug and inspect the database (e.g., using SQLite), would it be okay to temporarily skip the teardown in setup_db()? Or is there a better way to handle this without breaking best practices?

**Comment by RezaBG** [comment]
Based on Iffy’s explanation, the behavior is intentional and aligns with standard testing practices to ensure reproducibility. No changes are needed. Closing this issue. Thanks for the clarification!

**Comment by gnerkus** [comment]
> Hey Iffy @gnerkus
> 
> Thanks for the explanation—that makes a lot of sense now. I get why teardown is crucial for keeping tests isolated and reproducible.
> 
> If I want to debug and inspect the database (e.g., using SQLite), would it be okay to temporarily skip the teardown in setup_db()? Or is there a better way to handle this without breaking best practices?

The debug will have to happen within the test itself. See [this StackOverflow question](https://stackoverflow.com/questions/2678792/can-i-debug-with-python-debugger-when-using-py-test-somehow) for debugging approaches.
