### ISSUE TITLE
Alembic Migration Not Adding Column

### ISSUE THREAD

**Issue by RezaBG** [RezaBG/TUDU#9]
I’ve added a column (random) to your User model, created the Alembic migration, but the column isn’t showing up in the database.
 
 
<img width="1282" alt="Screenshot 2024-09-19 at 21 22 37" src="https://github.com/user-attachments/assets/f25592a8-43b0-4773-a672-63c5d78d845b">

**Comment by gnerkus** [comment]
@RezaBG Did you run `alembic upgrade head` after creating the migration?

**Comment by RezaBG** [comment]
I did `alembic upgrade head` but it still hasn't appeared. also, I to check it by `alembic show 95d92b438bf1` and i got: 

<img width="1216" alt="Screenshot 2024-09-20 at 09 38 23" src="https://github.com/user-attachments/assets/6244b8cc-d146-43db-911e-03cb0eb99552">
this below message that show me it's added.
